version: '3'
services:
  my-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    environment:
      - MONGO_DB_USERNAME=mongoadmin
      - MONGO_DB_PWD=admin
    networks:
      - mongoapp
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - mongoapp
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
    links:
      - "mongodb:mongodb"
    networks:
      - mongoapp
networks:
  mongoapp:
    driver: bridge
